### ISSUE TITLE
Bug: remove_components removes ALL keypoints

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/pose#156]
https://colab.research.google.com/drive/1rHcxLgpVNaGyxTym4qQSGddn6wBxDqs6?usp=sharing

```python
print(pose.body.data.shape) # (67, 1, 576, 3)
pose = pose.remove_components(["POSE_WORLD_LANDMARKS"])
print(pose.body.data.shape) # (67, 1, 0, 3) 
```

The resulting header looks like this:

```
PoseHeader
Version: 0.20000000298023224
PoseHeaderDimensions(width=1280, height=720, depth=0)
Bounding Box: False
Components:
PoseHeaderComponent: POSE_LANDMARKS
  Format: XYZC
  Points: []
  Limbs: 0
  Colors: 1

PoseHeaderComponent: FACE_LANDMARKS
  Format: XYZC
  Points: []
  Limbs: 0
  Colors: 1

PoseHeaderComponent: LEFT_HAND_LANDMARKS
  Format: XYZC
  Points: []
  Limbs: 0
  Colors: 21

PoseHeaderComponent: RIGHT_HAND_LANDMARKS
  Format: XYZC
  Points: []
  Limbs: 0
  Colors: 21
```
